# -*- coding: utf-8 -*-
"""Password Generator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LWSy2gH3uGX3-P4zQscBHL50bJU-Mjoq

**CODSOFT**

Name:- Prachi Athalye

A password generator is a useful tool that generates strong and

random passwords for users. This project aims to create a
password generator application using Python, allowing users to

specify the length and complexity of the password.

User Input: Prompt the user to specify the desired length of the

password.

Generate Password: Use a combination of random characters to

generate a password of the specified length.

Display the Password: Print the generated password on the screen.
"""

#i) Create a dictionary of username and password.
Dictionary={}
for i in range(2):
  username1=input("Enter a Usename:")
  password1=input("Enter a password:")
  Dictionary[username1]=password1
print(Dictionary)
if len(password1)>=8:
  print("Password is strong enough")
else:
  print("Re-enter the password")


if any(a.isdigit() for a in password1) and any(a.isalpha() for a in password1):
        print("Strong")
else:
  print("Weak")

n=len(password1)
for i in range(0,n):
  if password1[i]=="!":
    exit()
  elif password1[i]=="@":
    exit()
  elif password1[i]=="#":
    exit()
  elif password1[i]=="$":
    exit()
  elif password1[i]=="%":
    exit()
else:
    print("There should be at one special case character in the password")
    exit()

#ii)Validate the username and the password.
username2=input("Enter a username:")
password2=input("Enter a password:")
if username2==username1:
  print("The username is valid")
else:
  print("The username is invalid")
if password2==password1:
  print("The password is valid")
else:
  print("The password is invalid")
